M48
; DRILL file {KiCad 9.0.7} date 2026-05-19T04:47:18-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-19T04:47:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X220.46Y-70.81
X220.46Y-76.76
X220.46Y-82.71
X220.46Y-88.66
M30
